Models/IndividualButtonPartial.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace AutoService.Models
{
    /// <summary>
    /// Class IndividualButtonPartial represent a button using
    /// bootstrap 4 as well as several properties for personalization
    /// </summary>
    public class IndividualButtonPartial
    {
        /// <summary>
        /// Gets or sets the type of the button.
        /// </summary>
        /// <value>The type of the button.</value>
        public string ButtonType { get; set; }
        /// <summary>
        /// Gets or sets the action.
        /// </summary>
        /// <value>The action.</value>
        public string Action { get; set; }
        /// <summary>
        /// Gets or sets the glyph.
        /// </summary>
        /// <value>The glyph.</value>
        public string Glyph { get; set; }
        /// <summary>
        /// Gets or sets the text.
        /// </summary>
        /// <value>The text.</value>
        public string Text { get; set; }
        /// <summary>
        /// Gets or sets the service identifier.
        /// </summary>
        /// <value>The service identifier.</value>
        public int? ServiceId { get; set; }
        /// <summary>
        /// Gets or sets the customer identifier.
        /// </summary>
        /// <value>The customer identifier.</value>
        public string CustomerId { get; set; }
        /// <summary>
        /// Gets or sets the car identifier.
        /// </summary>
        /// <value>The car identifier.</value>
        public int? CarId { get; set; }
        /// <summary>
        /// Gets the action parameters.
        /// </summary>
        /// <value>The action parameters.</value>
        public string ActionParameters
        {
            get
            {
                var param = new StringBuilder(@"/");

                if (this.ServiceId != 0 && this.ServiceId != null)
                {
                    param.Append($"{ServiceId}");
                }

                if (!string.IsNullOrEmpty(this.CustomerId))
                {
                    param.Append($"{CustomerId}");
                }

                if (this.CarId != 0 && this.CarId != null)
                {
                    param.Append($"{CarId}");
                }

                return param.ToString();
            }
        }
    }
}

Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoService.Data;
using AutoService.Data.Migrations;
using AutoService.Models;
using AutoService.Utility;
using AutoService.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoService.Controllers
{

    /// <summary>
    /// Class CarsController.
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Authorize]
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _db;

        /// <summary>
        /// Initializes a new instance of the <see cref="CarsController"/> class.
        /// </summary>
        /// <param name="db">The database.</param>
        public CarsController(ApplicationDbContext db)
        {
            _db = db;
        }

        /// <summary>
        /// Indexes the specified user identifier.
        /// </summary>
        /// <param name="userId">The user identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Index(string userId = null)
        {
            if (userId == null)
            {
                // Only called when a guest user logs in
                userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            }

            var model = new CarAndCustomerViewModel()
            {
                Cars = await _db.Cars.Where(w => w.UserId == userId).ToListAsync(),
                UserObj = await _db.Users.Cast<ApplicationUser>().FirstOrDefaultAsync(f => f.Id == userId)
            };

            return View(model);
        }

        //Create GET
        /// <summary>
        /// Creates the specified user identifier.
        /// </summary>
        /// <param name="userId">The user identifier.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Create(string userId)
        {
            Car car = new Car
            {
                Year = DateTime.Now.Year,
                UserId = userId
            };

            return View(car);
        }

        /// <summary>
        /// Creates the specified car.
        /// </summary>
        /// <param name="car">The car.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car car)
        {
            if (ModelState.IsValid)
            {
                _db.Cars.Add(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new {userId = car.UserId});
            }

            return View(car);
        }

        //Details GET
        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id.Value);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        //Edit GET
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id.Value);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        //Edit POST
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="car">The car.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Car car)
        {
            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var c = await _db.Cars.SingleOrDefaultAsync(s => s.Id == id);

                if (c != null)
                {
                    c.Model = car.Model;
                    c.Color = car.Color;
                    c.Make = car.Make;
                    c.Mileage = car.Mileage;
                    c.Style = car.Style;
                    c.Year = car.Year;
                    c.VIN = car.VIN;

                    _db.Cars.Update(c);
                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index", new { userId = car.UserId });
                }
                else
                {
                    NotFound();
                }
            }

            return View(car);
        }

        //Delete GET
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id.Value);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        //DELETE POST
        /// <summary>
        /// Performs the deletion once it has been confirmed
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars.SingleOrDefaultAsync(s => s.Id == id);

            if (car == null)
            {
                return NotFound();
            }

            var svcs = _db.Services.Where(w => w.CarId == car.Id);
            _db.Services.RemoveRange(svcs);
            _db.Cars.Remove(car);

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new {userId = car.UserId});
        }

        /// <summary>
        /// Releases all resources currently used by this <see cref="T:Microsoft.AspNetCore.Mvc.Controller" /> instance.
        /// </summary>
        /// <param name="disposing"><c>true</c> if this method is being invoked by the <see cref="M:Microsoft.AspNetCore.Mvc.Controller.Dispose" /> method,
        /// otherwise <c>false</c>.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }
}

Controllers/ServiceTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoService.Data;
using AutoService.Models;
using AutoService.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoService.Controllers
{
    /// <summary>
    /// Class ServiceTypesController.
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Authorize(Roles = StaticDetails.AdminEndUser)]
    public class ServiceTypesController : Controller
    {
        private readonly ApplicationDbContext _db;

        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceTypesController"/> class.
        /// </summary>
        /// <param name="db">The database.</param>
        public ServiceTypesController(ApplicationDbContext db)
        {
            _db = db;
        }

        //GET: ServiceTypes
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Index()
        {
            return View(_db.ServiceTypes.ToList());
        }

        //GET: ServiceTypes/Create
        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Create()
        {
            return View();
        }

        //POST: Services/Create
        /// <summary>
        /// Creates the specified service type.
        /// </summary>
        /// <param name="serviceType">Type of the service.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ServiceType serviceType)
        {
            if (ModelState.IsValid)
            {
                _db.Add(serviceType);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(serviceType);
        }

        //Details: ServiceTypes/Details/1
        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var st = await _db.ServiceTypes.SingleOrDefaultAsync(s=>s.Id == id);

            if (st != null)
            {
                return View(st);
            }

            return NotFound();
        }

        //Edit: ServiceTypes/Edit/1
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var st = await _db.ServiceTypes.SingleOrDefaultAsync(s => s.Id == id);

            if (st != null)
            {
                return View(st);
            }

            return NotFound();
        }

        //POST:
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="serviceType">Type of the service.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ServiceType serviceType)
        {
            if (id != serviceType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Update(serviceType);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(serviceType);
        }

        //Delete: ServiceTypes/Delete/1
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var st = await _db.ServiceTypes.SingleOrDefaultAsync(s => s.Id == id);

            if (st != null)
            {
                return View(st);
            }

            return NotFound();
        }

        /// <summary>
        /// Removes the type of the service.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveServiceType(int? id)
        {
            var servType = await _db.ServiceTypes.SingleOrDefaultAsync(s => s.Id == id);

            _db.ServiceTypes.Remove(servType);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Releases unmanaged and - optionally - managed resources.
        /// </summary>
        /// <param name="dispose"><c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
        protected override void Dispose(bool dispose)
        {
            if (dispose)
            {
                _db.Dispose();
            }
        }
    }
}

Views/Shared/_CarDetailsInService.cshtml
@model AutoService.ViewModel.CarAndServicesViewModel

<h4>Car record for Customer</h4>
<div class="row form-border">
    <!-- We want to display two properties on left side and right side-->
    <div class="col-sm-5">
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="SubCar.Make" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom: 5px;">
                <input asp-for="SubCar.Make" disabled class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="SubCar.Model" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom: 5px;">
                <input asp-for="SubCar.Model" disabled class="form-control"/>
            </div>
        </div>
    </div>
    <div class="col-sm-5 col-sm-offset-2">
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="SubCar.Style" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom: 5px;">
                <input asp-for="SubCar.Style" disabled class="form-control"/>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <label asp-for="SubCar.Year" class="control-label"></label>
            </div>
            <div class="col-sm-9" style="padding-bottom: 5px;">
                <input asp-for="SubCar.Year" disabled class="form-control"/>
            </div>
        </div>
    </div>     
</div>

Views/Shared/_DisplayPastServices.cshtml
@using AutoService.Utility
@model AutoService.ViewModel.CarAndServicesViewModel
<div>
    <table class="table table-hover table-condensed">
        <tr>
            <th>
                @Html.DisplayNameFor(m=>Model.PastServices.FirstOrDefault().Miles)
            </th>
            <th>
                @Html.DisplayNameFor(m=>Model.PastServices.FirstOrDefault().Price)
            </th>
            <th>
                @Html.DisplayNameFor(m=>Model.PastServices.FirstOrDefault().Details)
            </th>
            <th>
                @Html.DisplayNameFor(m=>Model.PastServices.FirstOrDefault().DateAdded)
            </th>
            <th>
                @Html.DisplayNameFor(m=>Model.PastServices.FirstOrDefault().ServiceType.Name)
            </th>
            <th></th><!--For the delete button if present-->
        </tr>
        
        @foreach (var item in Model.PastServices)
        {
        <tr>
            <td>@Html.DisplayFor(f => item.Miles)</td>
            <td>@Html.DisplayFor(f => item.Price)</td>
            <td>@Html.DisplayFor(f => item.Details)</td>
            <td>@Html.DisplayFor(f => item.DateAdded)</td>
            <td>@Html.DisplayFor(f => item.ServiceType.Name)</td>
            <td>
                @if (item.DateAdded.Date == DateTime.Now.Date && User.IsInRole(StaticDetails.AdminEndUser))
                 {
                     @await Html.PartialAsync("_IndividualButtonPartial",
                         model: new IndividualButtonPartial()
                         {
                             Action = "Delete",
                             ButtonType = "btn-danger",
                             Glyph = "trash",
                             Text = "Delete",
                             ServiceId = item.Id
                         })
                 }
            </td>
        </tr>
        }
    </table>
</div>

Views/Shared/_IndividualButtonPartial.cshtml
@model IndividualButtonPartial
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<a type="button" class="btn btn-sm @Model.ButtonType" href="@Url.Action(Model.Action)@Model.ActionParameters">
    <span class="glyphicon glyphicon-@Model.Glyph"></span>
    <span class="sr-only">@Model.Text</span>
</a>

Views/Shared/_Layout.cshtml
@using AutoService.Utility
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoService</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AutoService</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole(StaticDetails.AdminEndUser))
                    {
                        <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                    }

                    <li><a asp-area="" asp-controller="Cars" asp-action="Index">Cars</a></li>

                    @if (User.IsInRole(StaticDetails.AdminEndUser))
                    {
                    <li><a asp-area="" asp-controller="ServiceTypes" asp-action="Index">Service Types</a></li>
                    }
                </ul>
                <partial name="_LoginPartial" />
                
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer class="footer" style="position: absolute; bottom: 0">
        <div class="container">
            <p class="text-muted">&copy; @DateTime.Now.Year - AutoService</p>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_TableButtonPartial.cshtml
@model IndividualButtonPartial

<td style="width: 150px">
    <div class="btn-group" role="group">
        @Html.Partial("_IndividualButtonPartial", model: new IndividualButtonPartial()
        {
            Action = "Edit", ButtonType = "btn-primary", Glyph = "pencil", Text = "Edit button", ServiceId = Model.ServiceId, CustomerId = Model.CustomerId, CarId = Model.CarId
        })
        @Html.Partial("_IndividualButtonPartial", model: new IndividualButtonPartial()
        {
            Action = "Details", ButtonType = "btn-success", Glyph = "list", Text = "Details button", ServiceId = Model.ServiceId, CustomerId = Model.CustomerId, CarId = Model.CarId
        })
        @Html.Partial("_IndividualButtonPartial", model: new IndividualButtonPartial()
        {
            Action = "Delete", ButtonType = "btn-danger", Glyph = "trash", Text = "Delete button", ServiceId = Model.ServiceId, CustomerId = Model.CustomerId, CarId = Model.CarId
        })
    </div>
</td>