Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using AutoService.Data.Migrations;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace AutoService.Models
{
    /// <summary>
    /// Class Car.
    /// </summary>
    public class Car
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>The identifier.</value>
        [Required]
        public int Id { get; set; }
        /// <summary>
        /// Gets or sets the vin.
        /// </summary>
        /// <value>The vin.</value>
        [Required]
        [Display(Name = "VIN", Description = "Vehicle Identifcation Number", Prompt = "Enter the VIN")]
        public string VIN { get; set; }
        /// <summary>
        /// Gets or sets the make.
        /// </summary>
        /// <value>The make.</value>
        [Required]
        [Display(Name = "Make", Description = "Car manufacturer", Prompt = "Enter the car manufacturer")]
        public string Make { get; set; }
        /// <summary>
        /// Gets or sets the model.
        /// </summary>
        /// <value>The model.</value>
        [Required]
        [Display(Name = "Model", Description = "Car model", Prompt = "Enter the car model")]
        public string Model { get; set; }
        /// <summary>
        /// Gets or sets the style.
        /// </summary>
        /// <value>The style.</value>
        [Display(Name = "Style", Description = "Car Style", Prompt = "Coupe / SUV / Etc")]
        public string Style { get; set; }
        /// <summary>
        /// Gets or sets the year.
        /// </summary>
        /// <value>The year.</value>
        [Required]
        [Display(Name = "Year", Description = "Year of manufacture", Prompt = "Enter manufacture year")]
        public int Year { get; set; }
        /// <summary>
        /// Gets or sets the mileage.
        /// </summary>
        /// <value>The mileage.</value>
        [Required]
        [Display(Name = "Mileage", Description = "Current Mileage", Prompt = "Enter the mileage")]
        public double Mileage{ get; set; }
        /// <summary>
        /// Gets or sets the color.
        /// </summary>
        /// <value>The color.</value>
        [Display(Name = "Color", Description = "Car color", Prompt = "Enter car color")]
        public string Color { get; set; }

        /// <summary>
        /// Gets or sets the user identifier.
        /// </summary>
        /// <value>The user identifier.</value>
        public string UserId { get; set; }

        /// <summary>
        /// Gets or sets the application user.
        /// </summary>
        /// <value>The application user.</value>
        [ForeignKey("UserId")]
        public virtual ApplicationUser ApplicationUser { get; set; }

        /// <summary>
        /// Gets the sub car.
        /// </summary>
        /// <value>The sub car.</value>
        public SubCar SubCar => SubCar.FromCar(this);
    }
}

Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoService.Data;
using AutoService.Data.Migrations;
using AutoService.Models;
using AutoService.Utility;
using AutoService.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AutoService.Controllers
{

    /// <summary>
    /// Class CarsController.
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    [Authorize]
    public class CarsController : Controller
    {
        private readonly ApplicationDbContext _db;

        /// <summary>
        /// Initializes a new instance of the <see cref="CarsController"/> class.
        /// </summary>
        /// <param name="db">The database.</param>
        public CarsController(ApplicationDbContext db)
        {
            _db = db;
        }

        /// <summary>
        /// Indexes the specified user identifier.
        /// </summary>
        /// <param name="userId">The user identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Index(string userId = null)
        {
            if (userId == null)
            {
                // Only called when a guest user logs in
                userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            }

            var model = new CarAndCustomerViewModel()
            {
                Cars = await _db.Cars.Where(w => w.UserId == userId).ToListAsync(),
                UserObj = await _db.Users.Cast<ApplicationUser>().FirstOrDefaultAsync(f => f.Id == userId)
            };

            return View(model);
        }

        //Create GET
        /// <summary>
        /// Creates the specified user identifier.
        /// </summary>
        /// <param name="userId">The user identifier.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Create(string userId)
        {
            Car car = new Car
            {
                Year = DateTime.Now.Year,
                UserId = userId
            };

            return View(car);
        }

        /// <summary>
        /// Creates the specified car.
        /// </summary>
        /// <param name="car">The car.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car car)
        {
            if (ModelState.IsValid)
            {
                _db.Cars.Add(car);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new {userId = car.UserId});
            }

            return View(car);
        }

        //Details GET
        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id.Value);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        //Edit GET
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id.Value);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        //Edit POST
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="car">The car.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Car car)
        {
            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var c = await _db.Cars.SingleOrDefaultAsync(s => s.Id == id);

                if (c != null)
                {
                    c.Model = car.Model;
                    c.Color = car.Color;
                    c.Make = car.Make;
                    c.Mileage = car.Mileage;
                    c.Style = car.Style;
                    c.Year = car.Year;
                    c.VIN = car.VIN;

                    _db.Cars.Update(c);
                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index", new { userId = car.UserId });
                }
                else
                {
                    NotFound();
                }
            }

            return View(car);
        }

        //Delete GET
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars
                .Include(c => c.ApplicationUser)
                .SingleOrDefaultAsync(m => m.Id == id.Value);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        //DELETE POST
        /// <summary>
        /// Performs the deletion once it has been confirmed
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _db.Cars.SingleOrDefaultAsync(s => s.Id == id);

            if (car == null)
            {
                return NotFound();
            }

            var svcs = _db.Services.Where(w => w.CarId == car.Id);
            _db.Services.RemoveRange(svcs);
            _db.Cars.Remove(car);

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new {userId = car.UserId});
        }

        /// <summary>
        /// Releases all resources currently used by this <see cref="T:Microsoft.AspNetCore.Mvc.Controller" /> instance.
        /// </summary>
        /// <param name="disposing"><c>true</c> if this method is being invoked by the <see cref="M:Microsoft.AspNetCore.Mvc.Controller.Dispose" /> method,
        /// otherwise <c>false</c>.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }
}

Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoService.Data;
using AutoService.Models;
using AutoService.Utility;
using AutoService.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace AutoService.Controllers
{
    /// <summary>
    /// Class ServicesController.
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    public class ServicesController : Controller
    {
        private readonly ApplicationDbContext _db;

        /// <summary>
        /// Initializes a new instance of the <see cref="ServicesController" /> class.
        /// </summary>
        /// <param name="db">The database.</param>
        public ServicesController(ApplicationDbContext db)
        {
            _db = db;
        }

        /// <summary>
        /// Indexes the specified car identifier.
        /// </summary>
        /// <param name="carId">The car identifier.</param>
        /// <returns>IActionResult.</returns>
        [Authorize]
        public IActionResult Index(int carId)
        {
            var model = new CarAndServicesViewModel
            {
                SubCar = _db.Cars.FirstOrDefault(f => f.Id == carId).SubCar,
                ServiceTypes = _db.ServiceTypes.ToList(),
                PastServices = _db.Services.Where(w => w.CarId == carId).OrderByDescending(o => o.DateAdded)
            };

            return View(model);
        }

        //GET: Services/Create
        /// <summary>
        /// Creates the specified car identifier.
        /// </summary>
        /// <param name="carId">The car identifier.</param>
        /// <returns>IActionResult.</returns>
        [Authorize(Roles = StaticDetails.AdminEndUser)]
        public IActionResult Create(int carId)
        {
            var model = new CarAndServicesViewModel
            {
                SubCar = _db.Cars.FirstOrDefault(f => f.Id == carId).SubCar,
                ServiceTypes = _db.ServiceTypes.ToList(),
                PastServices = _db.Services.Where(w => w.CarId == carId).OrderByDescending(o => o.DateAdded).Take(5)
            };

            return View(model);
        }

        //POST: Services/Create
        /// <summary>
        /// Creates the specified model.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CarAndServicesViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.NewService.CarId = model.SubCar.Id;
                model.NewService.DateAdded = DateTime.Now;
                _db.Add(model.NewService);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Create), new {carId = model.SubCar.Id});
            }

            var newModel = new CarAndServicesViewModel
            {
                SubCar = _db.Cars.FirstOrDefault(f => f.Id == model.SubCar.Id).SubCar,
                ServiceTypes = _db.ServiceTypes.ToList(),
                PastServices = _db.Services.Where(w => w.CarId == model.SubCar.Id).OrderByDescending(o => o.DateAdded).Take(5)
            };

            return View(newModel);
        }

        //DELETE: Get
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [Authorize(Roles = StaticDetails.AdminEndUser)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var svc = 
                await _db
                    .Services
                    .Include(s => s.Car)
                    .Include(s => s.ServiceType)
                    .SingleOrDefaultAsync(m => m.Id == id);

            if (svc == null)
            {
                return NotFound();
            }

            return View(svc);
        }

        /// <summary>
        /// Deletes the confirmed.
        /// </summary>
        /// <param name="model">The model.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = StaticDetails.AdminEndUser)]
        public async Task<IActionResult> DeleteConfirmed(Service model)
        {
            var serviceId = model.Id;
            var carId = model.CarId;

            var svc = await _db.Services.SingleOrDefaultAsync(m => m.Id == serviceId);

            if (svc == null)
            {
                return NotFound();
            }

            _db.Services.Remove(svc);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Create), new {carId = carId});
        }

        /// <summary>
        /// Releases all resources currently used by this <see cref="T:Microsoft.AspNetCore.Mvc.Controller" /> instance.
        /// </summary>
        /// <param name="disposing"><c>true</c> if this method is being invoked by the <see cref="M:Microsoft.AspNetCore.Mvc.Controller.Dispose" /> method,
        /// otherwise <c>false</c>.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
        }
    }
}

Views/Cars/Create.cshtml
@model Car
@{
    ViewData["Title"] = "Create";
}

<br />
<h2>Add New Car</h2>
<hr />

<form asp-action="Create">
    <div class="form-border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="VIN" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="VIN" class="form-control" />
                </div>
                <span asp-validation-for="VIN" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Make" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Make" class="form-control" />
                </div>
                <span asp-validation-for="Make" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Model" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Model" class="form-control" />
                </div>
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Style" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Style" class="form-control" />
                </div>
                <span asp-validation-for="Style" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Year" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Year" class="form-control" />
                </div>
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Mileage" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Mileage" class="form-control" />
                </div>
                <span asp-validation-for="Mileage" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Color" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Color" class="form-control" />
                </div>
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
        </div>
        <br />
        <div class="form-group">
            <input type="submit" value="Add Car" class="btn btn-sm btn-primary" />
            <a asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to list</a>
        </div>
    </div>
    <input asp-for="UserId" value="@Model.UserId" type="hidden"/>
</form>

Views/Cars/Delete.cshtml
@model Car
@{
    ViewData["Title"] = "Delete";
}

<br />
<h2>Delete Car</h2>
<hr />

<form asp-action="Delete">
    <div class="form-border">
        <fieldset disabled>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="VIN" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="VIN" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Make" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Make" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Model" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Model" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Style" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Style" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Year" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Year" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Mileage" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Mileage" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-2">
                        <label asp-for="Color" class="custom-label"></label>
                    </div>
                    <div class="col-sm-4">
                        <input asp-for="Color" class="form-control" />
                    </div>
                </div>
            </div>
        </fieldset> 
        <br/>
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-sm btn-danger"/>
            <a asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to list</a>
        </div>
    </div>
</form>

Views/Cars/Details.cshtml
@model Car
@{
    ViewData["Title"] = "Details";
}

<br />
<h2>Car Details</h2>
<hr />

<div class="form-border">
    <fieldset disabled>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="VIN" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="VIN" class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Make" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Make" class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Model" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Model" class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Style" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Style" class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Year" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Year" class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Mileage" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Mileage" class="form-control" />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-sm-2">
                    <label asp-for="Color" class="custom-label"></label>
                </div>
                <div class="col-sm-4">
                    <input asp-for="Color" class="form-control" />
                </div>
            </div>
        </div>
    </fieldset>
    <br/>
    <div class="form-group">
        <a asp-action="Edit" asp-route-userId="@Model.Id" class="btn btn-sm btn-primary">Update</a>
        <a asp-action="Index" asp-route-userId="@Model.UserId" class="btn btn-sm btn-success">Back to list</a>
    </div>
</div>

Views/Cars/Index.cshtml
@model AutoService.ViewModel.CarAndCustomerViewModel
@using AutoService.Utility
@{
    ViewData["Title"] = "Index";
}

<br/>
<h2>Car Record for Customer</h2>
<hr/>

<div class="row" style="padding-bottom: 80px;">
    <div class="col-sm-6" style="padding-bottom: 80px;">
        @* Add Create New Car Button *@
        <a asp-action="Create" asp-route-userId="@Model.UserObj.Id" class="btn btn-primary" style="width: 150px;">Add New Car</a>
    </div>
    <div class="col-sm-6" style="padding-bottom: 80px;">
        @* Display User Details *@
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="UserObj.FirstName" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom: 5px;">
                <input asp-for="UserObj.FirstName" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="UserObj.LastName" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom: 5px;">
                <input asp-for="UserObj.LastName" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="UserObj.PhoneNumber" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom: 5px;">
                <input asp-for="UserObj.PhoneNumber" disabled class="form-control" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <label asp-for="UserObj.Email" class="control-label"></label>
            </div>
            <div class="col-sm-8" style="padding-bottom: 5px;">
                <input asp-for="UserObj.Email" disabled class="form-control" />
            </div>
        </div>
    </div>
</div>

@if (Model.Cars.Any())
{
    <div class="form-border">
        <table class="table table-condensed table-hover">
            <tr>
                <th>@Html.DisplayNameFor(m => m.Cars.FirstOrDefault().VIN)</th>
                <th>@Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Make)</th>
                <th>@Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Model)</th>
                <th>@Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Style)</th>
                <th>@Html.DisplayNameFor(m => m.Cars.FirstOrDefault().Color)</th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var item in Model.Cars)
            {
                <tr>
                    <td>@Html.DisplayFor(m => item.VIN)</td>
                    <td>@Html.DisplayFor(m => item.Make)</td>
                    <td>@Html.DisplayFor(m => item.Model)</td>
                    <td>@Html.DisplayFor(m => item.Style)</td>
                    <td>@Html.DisplayFor(m => item.Color)</td>
                    
                    @if (User.IsInRole(StaticDetails.CustomerEndUser))
                    {
                        <td style="width: 100px;">
                            <a class="btn btn-primary btn-sm" asp-controller="Services" asp-action="Index" asp-route-carId="@item.Id">
                                <span class="glyphicon glyphicon-wrench"></span> &nbsp; Service History
                            </a>
                        </td>
                    }
                    else
                    {
                        <td style="width: 100px;">
                            <a class="btn btn-success btn-sm" asp-controller="Services" asp-action="Create" asp-route-carId="@item.Id">
                                <span class="glyphicon glyphicon-plus-sign"></span> &nbsp; New Service
                            </a>
                        </td>
                    }
                    <td>
                        @await Html.PartialAsync("_TableButtonPartial", new IndividualButtonPartial() {CarId = item.Id} )
                    </td>
                </tr>
            }
        </table>
    </div>
}
else
{
    <div class="text-primary form-border">
        No Car found! Please: <b><a asp-action="Create" asp-route-userId="@Model.UserObj.Id" class="text-primary" style="width: 150px;">add New Car</a></b>
    </div>
}